DROP TABLE IF EXISTS TB_WORKS CASCADE;

DROP TABLE IF EXISTS TB_FILE CASCADE;

CREATE TABLE TB_WORKS(
	idx BIGINT PRIMARY KEY,
	title VARCHAR(255),
	CONTENTS TEXT,
	TECH VARCHAR(255),
	NOTE TEXT,
	CLIENT VARCHAR(255),
	SORT INT
);

CREATE TABLE TB_FILE(
	file_idx BIGINT PRIMARY KEY AUTO_INCREMENT,
	work_idx BIGINT not null,
	file_name VARCHAR(255),
	file_path VARCHAR(255),
	file_type VARCHAR(30)
);
